// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bar struct {
	ID string `json:"id"`
}

type CreateBarInput struct {
	ID string `json:"id"`
}

type CreateFooInput struct {
	ID string `json:"id"`
}

type Foo struct {
	ID string `json:"id"`
}
